version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 18
    commands:
      - rm -rf /root/.cache/serverless-python-requirements
      - echo "Instalando Serverless Framework versão 3"
      - npm install -g serverless@3
  pre_build:
    commands:
      - echo "Inicializando credenciais serverless"
      - export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
      - echo "Instalando dependências Python com plugin serverless-python-requirements"
      - serverless plugin install -n serverless-python-requirements
  build:
    commands:
      - echo "Fazendo deploy com Serverless Framework"
      - serverless deploy --stage dev
artifacts:
  files:
    - '**/*'