service: email-contact-form

provider:
  name: aws
  runtime: python3.11
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false
  region: us-east-1
  environment:
    EMAIL_DESTINATARIO: contato@ponte-tech.com.br
    SES_SOURCE_EMAIL: contato@ponte-tech.com.br
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:us-east-1:123676445924:table/envio_contato"

functions:
  sendEmail:
    handler: src/handlers/email_sender.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - httpApi:
          path: /send
          method: post
      - httpApi:
         path: /send
         method: options

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    fileName: requirements.txt
    layer: true
