service: email-contact-form

provider:
  name: aws
  runtime: python3.11
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false
  region: us-east-1
  environment:
    EMAIL_DESTINATARIO: contato@ponte-tech.com.br
    SES_SOURCE_EMAIL: contato@ponte-tech.com.br
    USER_POOL_ID: us-east-1_4vX0x2g7E
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:us-east-1:123676445924:table/envio_contato"
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
          Resource: "arn:aws:dynamodb:us-east-1:123676445924:table/usuarios"
        - Effect: "Allow"
          Action:
            - "cognito-idp:AdminAddUserToGroup"
          Resource: "arn:aws:cognito-idp:us-east-1:123676445924:userpool/us-east-1_NtC5KY3kF"

functions:
  sendEmail:
    handler: src/handlers/email_sender.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - httpApi:
          path: /send
          method: post
      - httpApi:
         path: /send
         method: options
  cognitoAuth:
    handler: src/handlers/cognito_auth.handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - cognitoUserPool:
          pool: ponte-tech-user-pool
          trigger: PostConfirmation
    environment:
      USER_POOL_ID: ${env:USER_POOL_ID}
      DYNAMODB_TABLE: us-east-1_4vX0x2g7E

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    fileName: requirements.txt
    layer: true
